import GlobalStyle from "@/styles/global";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./lip/registry";
import { RdxProvider } from "@/redux/RdxProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Upwork",
  // description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body classNStyledComponentsRegistryame={inter.className}>
        {/* <ErrorBoundary statusCode={404} > */}
          <>
            <RdxProvider>
              <GlobalStyle />

              {children}
            </RdxProvider>
          </>
        {/* </ErrorBoundary> */}
      </body>
    </html>
  );
}